### ISSUE TITLE
Implement basic validation for Capact manifests

### ISSUE THREAD

**Issue by pkosiec** [capactio/capact#398]
#### `capact validate` for creating new manifests
1. Check if JSON schema in Types valid
   - Fix the JSON schemas if needed
1. Additional validation against Public Hub (enabled with an additional flag): [2SP]
    - Interface input + output: check typeRef + revision exists in Hub
    - Implementation: `additionalInput.typeInstances` :  check typeRef + revision exists in Hub
    - Implements: check path + revision exists in Hub
    - Requires: check all requirements (path + revision) exist in Hub
    - Imports: check all methods from InterfaceGroups exist in Hub
    - Implementation + Type: check path + revision for every Attribute in metadata if exists in Hub
    - Validate all manifests and collect all errors
    - Update development guide

### `hub-manifests` CI [1SP]

Spawn local Capact installation with CLI and run CLI manifests validation against existing Hub
    - Reuse what we have on `capactio/capact`
    - Idea: Populator should populate manifests from PR - disable populator in cluster, run populator locally

## Subtasks

- [x] Capact CLI - `capact validate` @pkosiec 
- [x] 4SP split to #425
- [ ] `hub-manifests` CI migration (dependency for the second subtask)

## Reason

Validation is essential for creating new Capact manifests to avoid mistakes.

**Comment by pkosiec** [comment]
The following PRs are ready to review:
- [ ] https://github.com/capactio/capact/pull/436
- [ ] https://github.com/capactio/capact/pull/437
- [ ] https://github.com/capactio/hub-manifests/pull/16
