### ISSUE TITLE
Implement Delegated Storage

### ISSUE THREAD

**Issue by pkosiec** [capactio/capact#604]
## Description

Implement Delegated Storage according to the [accepted proposal](https://github.com/capactio/capact/blob/main/docs/proposal/20211207-delegated-storage.md).

- [ ] Investigate our approach to implementation [3MD - to drop in minimal scope]
    - taking into account the [Potential feature evolution](#potential-future-evolution) which may impact implementation
- [ ] capactio/capact#601 [3MD]
        - Make sure Populator supports it
        - Support it in GraphQL API
        - [Find Types based on prefix of parent nodes](https://capact.io/docs/feature/type-features#find-types-based-on-prefix-of-parent-nodes) (consider refactoring [Cypher query](https://github.com/capactio/capact/blob/main/hub-js/graphql/public/schema.graphql#L569) to TypeScript)
- [ ] capactio/capact#544 [3MD]
- [ ] capactio/backlog#35 [15MD]
    - Consider https://github.com/dosco/graphjin
    - Implement 1:1 features that we already support in Local Hub already
    - Make Local Hub to use PostgreSQL (Install Bitnami PostgreSQL Helm chart)
        - Remember that in future we will extend it with multiple backends
    - Do not support upgrade and migration from 0.5.0
    - Extend TypeInstance GraphQL API with the `TypeInstance.spec.backend` field
- [ ] Implement Go Template storage backend services: [3 MD / 10 MD]
    - default storage backend service for PostgreSQL
    - service for TypeInstance projection
    - At the very beginning it can be simplified to built-in database driver in Local Hub [3MD]
    - Later, in the future, we can implement the gRPC+ProtoBuf external service concept + installation manifests [8MD+]: presumably in a separate repositor 
- [ ] Handle multiple backends for the TypeInstance upload from workflow [5MD]
    - Extend `capact-outputTypeInstances` syntax
    - Set proper `uses` relations between storage backend TypeInstance and other TypeInstances
    - Modify TypeInstance create/update/delete images (named as "Argo actions") to take new input
    - For backward compatiblity:
        - Modify Helm and Terraform runners and output additional ouptut under `value` property in Argo artifact
        - Make sure all manifests are up to date (at least compatible with new Argo artifact syntax)
- [ ] Helm Runner [builtin: 3MD / external: 8MD]
    - Remove `output.goTemplate`
    - Stop supporting usage of funcs from `_helpers.tpl` in case of Helm runner
    - Update JSON Schema for Type (generate from Go struct)
    - Define Storage Backend for Helm releases
        - Define Type
        - Use Helm client
     - If this is external storage backend: [8 MD]
         - Installation Manifests
         - Tooling, new repo, CI pipelines, tests. store gRPC API
         - Helm chart (hosted via GitHub Pages?)
- [ ] Adjust all Implementation manifests to use latest workflow syntax (Argo workflows artifact content) [13MD / timebox 8MD]
    - Only open source manifests
    - Use dynamic TypeInstance projection for output TypeInstances
    - We can try to keep backward compatibility if needed and for older manifests still treat whole Argo artifacts as TypeInstance value
    - In case of backward compatibility, we can adjust just a few manifests for showcase purposes
- [ ] Update Policy API and PolicyEnforcedClient [5MD]
    - Add new properties
    - Handle common TypeInstance injections
- [ ] Update documentation [1MD]
    - Policy
    - Content Development guide
    - Type features
- [ ] Implement storage backends
   - Vault [builtin: 5MD / external: 8MD - to drop in minimal scope]
   - Prerequisite: Helm Runner

Total SP: 
    - Minimal scope: 46 SP + padding 15% = 53 SP (~ 7 weeks)
    - Target architecture: 74 SP  + padding 15% = 85 SP

## Reason

See capactio/backlog#24

## Use cases

See capactio/backlog#24
